{% set version = "1.7.0" %}

package:
  name: importlib-metadata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-{{ version }}.tar.gz
  sha256: 90bb658cdbbf6d1735b6341ce708fc7024a3e14e99ffdc5783edea9f9b077f83

build:
  number: 1
  noarch: python

outputs:
  - name: importlib-metadata
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm >=3.4.1
      run:
        - python >=3.6
        - zipp >=0.5
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - importlib_metadata

  - name: importlib_metadata
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('importlib-metadata', max_pin="x.x.x") }}
    test:
      imports:
        - importlib_metadata

about:
  home: https://gitlab.com/python-devs/importlib_metadata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library to access the metadata for a Python package

extra:
  recipe-maintainers:
    - nehaljwani
    - nicoddemus
    - marcelotrevisani
